AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: AWS SAM template to deploy role

Parameters:
  Environment:
    Type: String
    Description: Name of the environment in which the application will be deployed
    Default: playground
  AppName:
    Type: String
    Description: Name of the application
    Default: CICD
  S3arn:
    Type: String
    Description: ARN of the S3 bucket artifact
    Default: arn:aws:s3:::cloudproviders-pmd-454492840024
  PipelineArtifactKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: 'The arn of the KMS Key used to encrypt artifacts for cross-account use'

Resources:
  PipelineRoleCrossAcc:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-pipeline-cross-account'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::454492840024:root   # Create a parameter for account
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3PolicyCrossAcc
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:Put*
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::cloudproviders-pmd-454492840024/*
        - PolicyName: KMSPolicyCrossAcc
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:GenerateDataKey*
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:Decrypt
                Resource:
                  - !Ref PipelineArtifactKey

  # LambdaReaderRoleArn:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: !Sub /${Environment}/historical-api/lambda-reader-role-arn
  #     Type: String
  #     Value: !GetAtt LambdaReaderRole.Arn
  #     Description: historical api lambda reader role arn
