AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: AWS SAM template to deploy role

Parameters:
  Environment:
    Type: String
    Description: Name of the environment in which the application will be deployed
    Default: playground

Resources:
  PipelineRoleCF:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-pipeline-cloudformation'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CFRolePipeline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
