version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - node --version
      - echo "RAFAEL"
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - >-
        aws cloudformation package --template webapp/template.yml --s3-bucket $S3_BUCKET
        --output-template template-export-get.yml
      - >-
        aws cloudformation package --template webapp/template.yml --s3-bucket $S3_BUCKET
        --output-template template-test.yml
      - >-
        aws cloudformation package --template webapp/template.yml --s3-bucket $S3_BUCKET
        --output-template template-stage.yml
      - >-
        aws cloudformation package --template webapp/template.yml --s3-bucket $S3_BUCKET
        --output-template template-prod.yml
artifacts:
  type: zip
  files:
    - template-export-get.yml
    - template-test.yml
    - template-stage.yml
    - template-prod.yml
